# Generated by Django 4.2.6 on 2023-12-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmarks',
            options={'verbose_name': 'landmarks'},
        ),
    ]
