# Generated by Django 4.2.6 on 2023-12-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_alter_landmarks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmarks',
            options={'verbose_name': 'landmark', 'verbose_name_plural': 'landmarks'},
        ),
    ]
